### ISSUE TITLE
Not working with Nikon D3

### ISSUE THREAD

**Issue by domsmac** [dognotdog/ptpwebcam#11]
I know its an old camera, so no surprise I guess.

When testing it with Quicktime & Skype both packages recognise the D3 but it just shows a black screen and says it cannot record

**Comment by dognotdog** [comment]
@domsmac could you try with [v1.0.0-alpha7](https://github.com/dognotdog/ptpwebcam/releases/tag/v1.0.0-alpha7)? It has a change in processing LiveView image data that might be able to get the D3 to work if I interpreted the datasheet wrong about the JPEG data offset.

**Comment by domsmac** [comment]
@dognotdog I'm afraid that hasn't changed anything.

<img width="478" alt="Screenshot 2020-07-21 at 16 33 07" src="https://user-images.githubusercontent.com/68590649/88075532-d47da080-cb70-11ea-8de7-a33338f4ab16.png">

**Comment by dognotdog** [comment]
@domsmac thanks for trying it out, what is your macOS version?

**Comment by domsmac** [comment]
Hi

Mac OS Catalina 10.15.5

Theres an update ready to do tonight.

**Comment by dognotdog** [comment]
@domsmac did the shutter cycle before you got that error message?

**Comment by domsmac** [comment]
What do you mean by cycle?

The camera was on, connected, the software could see it, I pressed the shutter but just the same thing happened
________________________________

**Comment by dognotdog** [comment]
@domsmac when the video source is selected to be the DSLR, what **should** happen is that a command is issued to the camera to start LiveView, causing it to flip the mirror up and open the shutter, that is what I mean by "shutter cycle." It should sound like taking a picture.

**Comment by domsmac** [comment]
@dognotdog/ptpwebcam<mailto:ptpwebcam@noreply.github.com> I see what you mean now.

No I’m afraid its not doing that. Ive just tried again this morning, made sure Live View (Lv) is selected on the command dial, set to PTP in the USB settings and its connected to the Mac, it recognises its there as the controls appear in the top bar of the Mac screen.

I’ve discovered a quirk with the D3 after doing some online checking this morning, the Lv mode only activates once you depress the shutter button all the way, as if you are taking an actual photo. Never having used this mode before I didn’t realise that. But when you connect the camera to the computer via USB it automatically shuts of the Lv and it wont activate it on the first place if you start with the camera connected. Does that make sense?

However, don’t spend your precious free time trying to find a fix for a 10+ year old camera, its probably only me that’s interested anyway. Focus your efforts on the more modern cameras where you stand a better chance of gaining some support. I’ll drop some sponsor money your way later for the effort you’ve put in so far though, its a great project, which lets be honest, Nikon should have done themselves!


Thanks

**Comment by dognotdog** [comment]
@domsmac did you try with [v1.0.0-beta5](https://github.com/dognotdog/ptpwebcam/releases/tag/v1.0.0-beta5)? There have been some improvements for the D90 that might also make things better for the D3, as they are the same generation firmware.

**Comment by domsmac** [comment]
Good news, it works!
It doesn't seem to autofocus, but I haven't had much time to play with it as the battery on teh camera was dying. Its on charge now so will try again later and report back.

Great work though, well done. I'll leave a donation for your efforts!
