### ISSUE TITLE
Nikon D7500 compatibility report

### ISSUE THREAD

**Issue by vinzenz-s** [dognotdog/ptpwebcam#17]
Works with a Nikon D7500, all exposure functions and AF are responsive.
resolution displayed in QT: 640x424 pixels.
small lag of the stream, and motion not perfectly smooth despite nominally recording at 30 fps.

**Comment by dognotdog** [comment]
@vinzenz-s thanks for the report. 

Good observation on the smoothness! The video timing could indeed be improved somewhat, as right now it is a very simplistic mechanism that grabs frames from the camera, without attempting to control jitter and dropped frames. USB 3 cameras should be able to easily grab images at a higher frame rate, too, eg. 60 fps.

With the D7500, resolution could also be enhanced, as the camera supports XGA (up to 1024x768) images for LiveView, with the default being VGA. There just needs to be a little work done to support dynamic resolution switching of the video stream.

**Comment by dognotdog** [comment]
added issue #23 to track work on enhanced resolution video.
