### ISSUE TITLE
Uninstall Script or Methods?

### ISSUE THREAD

**Issue by kopepasah** [dognotdog/ptpwebcam#18]
Is there an uninstall script (or other uninstall method) for removing PTP Webcam?

**Comment by dognotdog** [comment]
PTP Webcam is installed in:
`/Library/CoreMediaIO/Plug-Ins/DAL/PTPWebcamDALPlugin.plugin`
Just delete that file, and it is gone.

**Comment by dognotdog** [comment]
Added info to the readme in ff49446.

**Comment by kopepasah** [comment]
@dognotdog I think there may be some extra steps. I had to reinstall Zoom in order to stop getting the permissions modal. Other than that, this may be good enough for now.

**Comment by dognotdog** [comment]
@kopepasah What kind of dialog were you getting (and what is your OS version)?

I am not sure of the codesigning data can be restored easily, but it might be worth a try to experiment with that.

**Comment by dognotdog** [comment]
An uninstaller is now available from https://ptpwebcam.org though it doesn't deal with restoring codesigning, see #47 for continuing development on that path.
