### ISSUE TITLE
Not working with Nikon D5100

### ISSUE THREAD

**Issue by nagaraj-citrix** [dognotdog/ptpwebcam#2]
Cam does not show up in the list and QuickTime player crashes when CAM is connected

**Comment by dognotdog** [comment]
@nagaraj-citrix what is the OS X version you're using?

**Comment by dognotdog** [comment]
@nagaraj-citrix I've created a new release that has somewhat better diagnostic reporting, maybe it catches the crash and shows us where the error comes from. Please try https://github.com/dognotdog/ptpwebcam/releases/tag/v1.0.0-alpha3

**Comment by gitmyway** [comment]
Verified : Nikon D5100 works in QuickTime and Zoom . Tested on current up to date Mac.
