### ISSUE TITLE
Nikon D5100 compatibility report

### ISSUE THREAD

**Issue by aseidlitz** [dognotdog/ptpwebcam#27]
Camera is recognized and works fine. But none of the status bar menu options seem to have any effect on the video—I can't change any of the options while recording in QuickTime. Autofocus kicks at random. I had to disable AF on the lens (DX 18-55) and manually adjust it. When recording/preview is not running, I can trigger Autofocus (but I can't preview it at the same time). ISO settings seem to have no effect.

Also works in Zoom.

**Comment by dognotdog** [comment]
@aseidlitz thanks for the report!

Is the _Exposure Preview_ menu item available for the D5100? If not, that would indicate that the camera does not support exposure preview. Indeed, [this article](http://blog.dojoklo.com/2011/07/01/full-manual-exposure-control-video-and-the-d5100/) suggests that it needs some special settings to be able to record video with locked settings, but it is unclear to me if that is reflected in in the LiveView image.

As for the autofocus issue, I will look into making further settings available in the control menu to hopefully prevent a continous autofocus.

**Comment by dognotdog** [comment]
Issues should be fixed now, as the relevant camera settings are available in the control menu.
