### ISSUE TITLE
[BUG] Incompatible with obs-mac-virtualcam

### ISSUE THREAD

**Issue by gxalpha** [dognotdog/ptpwebcam#29]
This repo uses the same UDID [(src/info.plist)](https://github.com/dognotdog/ptpwebcam/blob/master/PtpWebcamDalPlugin/Info.plist#L23) as the [obs-mac-virtualcam](https://github.com/johnboiles/obs-mac-virtualcam) which it is probably based on, causing it to incompatible with the obs-mac-virtualcam.
Would you mind generating a new UDID?

For further information on this issue see [here](https://github.com/johnboiles/obs-mac-virtualcam/issues/191).

**Comment by dognotdog** [comment]
fixed in a50ae3c, thanks for the report @gxalpha

**Comment by dognotdog** [comment]
thanks @gxalpha for reporting, should be fixed with f093004 and v1.0.0-beta2 release.
