### ISSUE TITLE
Not working with D7000

### ISSUE THREAD

**Issue by avloenen** [dognotdog/ptpwebcam#3]
It connects, but gives this error:

-parseNikonPropertiesResponse: expected response data length (380) does not match buffer size (386).

When you switch to the D7000 as input it tries to take a few pictures and then crashes.

**Comment by dognotdog** [comment]
@avloenen commit 1f6a83b should fix that issue, thanks for the report. I've released [v1.0.0-alpha4 ](https://github.com/dognotdog/ptpwebcam/releases/tag/v1.0.0-alpha4)that includes the fix.
