### ISSUE TITLE
Nikon D810 compatibility report

### ISSUE THREAD

**Issue by chulster** [dognotdog/ptpwebcam#34]
Works, but output resolution is very low (640 x 424) at least in Quicktime Player. Is this normal?

**Comment by dognotdog** [comment]
@chulster unfortunately yes, the max resolution the D810 supports for the LiveView mode over USB is 640x480. The D850 is the first in the series that supports up to 1024x768. If you need 1080p, a HDMI input card or USB dongle is probably your best bet.
