### ISSUE TITLE
Nikon D7200 compatibility report

### ISSUE THREAD

**Issue by jfthompson1** [dognotdog/ptpwebcam#35]
No issue. Tested this with a D7200 on a 2012 MacBook Pro running OS 10.13.6. Works as promised in Quicktime player, following instructions from ptpwebcam.org. Thank you very much!

**Comment by dognotdog** [comment]
Thanks for the report @jfthompson1 !

**Comment by robzach** [comment]
Confirming my D7200 is also doing very well on a 2019 MacBook Pro, running 10.15.7. Works great!
