### ISSUE TITLE
Confirm D7500 works with XGA resolution.

### ISSUE THREAD

**Issue by vinzenz-s** [dognotdog/ptpwebcam#37]
Following up on https://github.com/dognotdog/ptpwebcam/issues/17, I tried the current beta5 and can confirm I can switch to XGA resolution and Quicktime correspondingly receives an XGA video feed.
<img width="348" alt="Screenshot 2020-08-20 at 22 51 38" src="https://user-images.githubusercontent.com/12461362/90824694-19475380-e338-11ea-9730-c2f70bf5db76.png">

**Comment by dognotdog** [comment]
I guess this also resolves #23.

@vinzenz-s thank's for reporting back!
