### ISSUE TITLE
Working with Nikon D750

### ISSUE THREAD

**Issue by sal0max** [dognotdog/ptpwebcam#5]
Using macOS 10.15.6 (19G73).

"D750" entry appears in the macOS menu bar and I can alter all the settings: they get changed in the camera.

Only problem: When I open QuickTime and start a new movie recording, D750 is recognized as camera, but I don't see an image. However, I hear the mirror clacking, so that works.
**I then tested it with the Photo Booth app and there I see the image. Everything works as expected.**
So, might just be a problem with my QuickTime installation.

Thanks so much for your awesome work!

I will test it with my Z6, next.

**Comment by dognotdog** [comment]
@sal0max thanks for the report! The behavior with Photo Booth vs. QuickTime Player is interesting.

On OS X 10.14, Photo Booth is using the hardened runtime with Library Validation enabled, and thus does not show additional video sources at all.

**Comment by sal0max** [comment]
It also works with the Preview app to import a signature, as described [here](https://support.apple.com/en-gb/guide/preview/prvw35725/mac).

**Comment by dognotdog** [comment]
@sal0max that's another one that's locked down in macOS 10.14, so while I can import images, I cannot choose a different camera.

I'll be running some tests with 10.15 as soon as I can get an install of that set up, as I did not expect these differences.

**Comment by sal0max** [comment]
I probably should mention that I'm running a Hackintosh. So maybe my setup is not 100% representative.

**Comment by dognotdog** [comment]
That might explain why Preview and Photo Booth both work, as I believe codesigning and associated security features aren't enabled on Hackintosh setups.
