### ISSUE TITLE
Support for Big Sur

### ISSUE THREAD

**Issue by webventil** [dognotdog/ptpwebcam#54]
Hi,
The new macOS is getting released soon. It would be awesome to get support for macOS 11 Big Sur. Currently my cameras (Nikon Z7, and Nikon D7000) are getting recognised by the helper tool, when I launch QuickTime. But both cameras can't be selected and are not displayed in the camera sources.

I attached a report with my Nikon Z6 and macOS Big Sur Bega 11.0 (20A5384c). Maybe that helps.

Thanks,
Arne

<details><summary>Z 6 Camera Report</summary>
```
# PTP Webcam Nikon Corporation Z 6 Camera Report

PTP Version:              100
Vendor Extension ID:      65535
Vendor Extension Version: 110
Vendor Description:       Microsoft.com/DeviceServices: 1.0
Functional Mode:          0
Device Version:           V3.11

## Supported Operations

- 0x1001 (PTP Get Device Info)
- 0x1002 (PTP Open Session)
- 0x1003 (PTP Close Session)
- 0x1006 (PTP Get Number of Objects)
- 0x1007 (PTP Get Object Handles)
- 0x1008 (PTP Get Object Info)
- 0x100C (?)
- 0x1014 (PTP Get Property Description)
- 0x1015 (PTP Get Property Value)
- 0x1016 (PTP Set Property Value)
- 0x90C7 (?)
- 0x941C (?)

## Supported Events

- 0x4001 (?)
- 0x4002 (?)
- 0x4003 (?)
- 0x4004 (?)
- 0x4005 (?)
- 0x4006 (?)
- 0x4007 (?)
- 0x4008 (?)
- 0x4009 (?)
- 0x400A (?)
- 0x400C (?)
- 0x400D (?)
- 0xC101 (?)
- 0xC102 (?)
- 0xC105 (?)
- 0xC108 (?)
- 0xC10A (?)
- 0xC10B (?)
- 0xC10C (?)
- 0xC10E (?)
- 0xC120 (?)
- 0xC121 (?)
- 0xC122 (?)
- 0xC123 (?)
- 0xC700 (?)

## Supported Properties

- 0x5001 (Battery Level):
	- value:   0x0050 (80 %)
	- default: 0x0064 (100 %)
	- dataType: 0x0002
	- rw: 0x0000
	- range:
		- min:  0x0001 (1 %)
		- max:  0x0064 (100 %)
		- step: 0x0001 (1 %)
- 0x5003 (?):
	- value:   (null)
	- default: (null)
- 0x5004 (?):
	- value:   (null)
	- default: (null)
- 0x5005 (White Balance):
	- value:   0x0000
	- default: 0x0000
- 0x5007 (Aperture):
	- value:   0.0
	- default: 0.0
- 0x5008 (Focal Length):
	- value:   0.00 mm
	- default: 0.00 mm
- 0x500A (Focus Mode):
	- value:   0x0000
	- default: 0x0000
- 0x500B (?):
	- value:   0x0000
	- default: 0x0000
- 0x500C (?):
	- value:   (null)
	- default: (null)
- 0x500D (Exposure Time):
	- value:   1/inf s
	- default: 1/inf s
- 0x500E (Exposure Program Mode):
	- value:   0x0000
	- default: 0x0000
- 0x500F (ISO):
	- value:   (null)
	- default: (null)
- 0x5010 (Exposure Correction):
	- value:   0.000
	- default: 0.000
- 0x5011 (?):
	- value:   20201012T163047
	- default: 20180101T000000
	- dataType: 0xFFFF
	- rw: 0x0001
	- range (n=0):
- 0x5013 (?):
	- value:   (null)
	- default: (null)
- 0x5018 (?):
	- value:   (null)
	- default: (null)
- 0x501C (?):
	- value:   0x0000
	- default: 0x0000
- 0x501E (?):
	- value:   (null)
	- default: (null)
- 0x501F (?):
	- value:   (null)
	- default: (null)
- 0xD303 (?):
	- value:   0x0001 (1)
	- default: 0x0001 (1)
	- dataType: 0x0002
	- rw: 0x0000
	- range (n=0):
- 0xD406 (?):
	- value:   Windows/6.0.5330.0 MTPClassDriver/6.0.5330.0
	- default: Windows/6.0.5330.0 MTPClassDriver/6.0.5330.0
	- dataType: 0xFFFF
	- rw: 0x0001
	- range (n=0):
- 0xD407 (?):
	- value:   0x0001 (1)
	- default: 0x0001 (1)
	- dataType: 0x0006
	- rw: 0x0000
	- range (n=0):

```
</details>

**Comment by dognotdog** [comment]
@webventil thanks for trying it out! Did you try Zoom or Skype to see if the camera is recognized there?

**Comment by webventil** [comment]
I tested it now with Skype (8.65.0.76) and Bluejeans (2.24.0.184). When I plugin the camera, the camera name appears in the macOS ToolBar. I am able to select the camera, but when the App is trying to preview the video from the camera after some seconds of black screen the camera name from the tool bar disappears. and the camera in the selection list as well.
I attached the log of this tries. 

[org.ptpwebcam.PtpWebcamAgent.stderr.log](https://github.com/dognotdog/ptpwebcam/files/5369116/org.ptpwebcam.PtpWebcamAgent.stderr.log)

**Comment by dognotdog** [comment]
@webventil I was not able to reproduce that error in Big Sur. Are you able to put the camera into LiveView without tethering? I wonder if there's another application that's preventing things from working. Eg., Canon's Webcam Utility blocks pretty much all PTP cameras even from other manufacturers when it's installed.

My D800 seems to work fine in Firefox, though QuickTime Player does not show the camera.

**Comment by dognotdog** [comment]
QuickTime on Big Sur fails with
```
Error loading /Library/CoreMediaIO/Plug-Ins/DAL/PTPWebcamDALPlugin.plugin/Contents/MacOS/PTPWebcamDALPlugin:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/PTPWebcamDALPlugin.plugin/Contents/MacOS/PTPWebcamDALPlugin, 0x0106): code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/PTPWebcamDALPlugin.plugin/Contents/MacOS/PTPWebcamDALPlugin) not valid for use in process: mapping process is a platform binary, but mapped file is not
```
which seems to indicate that it no longer allows 3rd party plugins?

**Comment by dognotdog** [comment]
@webventil as best as I can tell the behavior of QuickTime Player is a deliberate choice by Apple. I've filed a bug report as FB8798808. I'd encourage everyone for whom this is a problem to file a bug report at [https://feedbackassistant.apple.com](https://feedbackassistant.apple.com) referencing that report number.

**Comment by webventil** [comment]
I tested it now with several times again and I removed all video streaming software I installed during pandemic. Unfortunately with no success. Even the Preview Video Stream Tool is not launching. Log alway says `no data!`.

What do you mean by:
> Are you able to put the camera into LiveView without tethering?

[PtpWebcamLaunchAgent_2020-10-14-080204_me.crash.txt](https://github.com/dognotdog/ptpwebcam/files/5375990/PtpWebcamLaunchAgent_2020-10-14-080204_me.crash.txt)

**Comment by webventil** [comment]
Turns out... It now works. After actually turning the camera on, ptp started to work after some minutes. On my other Mac with Catalina it only word when the camera was plugged in but turned out. Crazy. Will give it some more tests rounds.

**Comment by webventil** [comment]
Ok, I can confirm, that my described way (turning the camera on) works. It takes some minutes until the cam is detected, but this is fine for me for now.
