### ISSUE TITLE
Working with Nikon Z7

### ISSUE THREAD

**Issue by jth0** [dognotdog/ptpwebcam#7]
Seems to work, although I am not getting QuickTime to capture audio right now. I will play with that more -- more likely an issue with my audio stack than PTP.

 I can change white balance, set exposure compensation, select ISO, ask it to autofocus. 

In Program mode, I can select nothing different, and my camera selects f/2.8.
In Aperture mode, I can select the aperture. 
In Shutter mode, I can select the shutter speed.
In Manual, I can select the shutter speed and aperture.

PTP doesn't pick up on a mode change until the camera selection changes or I try to change a setting. For example, if I'm in Aperture priority mode, then change the mode on the camera, I can try to change Aperture settings in PTP, and then PTP will pick up the camera in a new mode and refresh the settings displayed in the menu.

**Comment by jth0** [comment]
Turns out you still have to tell your cough button app to unmute your microphone when making a video 🙄

**Comment by dognotdog** [comment]
@jth0 excellent, thanks for the thorough report! There is no audio capture at the moment, as that's another can of worms. I will highlight that in the docs. Definitely something for the future, I've created issue #8 for it.

And you are also right about the mode changes, the control menu does currently not pick up settings changes except for the battery level, see #9.

**Comment by jth0** [comment]
I'm also not seeing the Z7 show up as a camera option in FaceTime.app - not sure if that's a bug or known yet, so just mentioning here for now.

**Comment by dognotdog** [comment]
FaceTime is super locked down, to the point where codesigning cannot be easily disabled. But it does warrant its own issue as #10.

**Comment by jth0** [comment]
Understood, I just know I see other cameras like Logitech for use in FaceTime.app.

**Comment by dognotdog** [comment]
Macs ship with a USB video device class driver, which most standalone webcams conform to, so they don't need 3rd party drivers, unlike DSLRs which mostly have their vendor-specific ways of getting live images out of them.
